// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunnyBlog.Infrastructure;

#nullable disable

namespace SunnyBlog.Infrastructure.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20230103215230_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("SunnyBlog.Domain.Entities.Article", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<long?>("CreateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("create_time");

                    b.Property<int>("DelFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("del_flag")
                        .HasDefaultValueSql("'0'")
                        .HasComment("delete flag(0 not deleted，1 deleted)");

                    b.Property<bool>("IsComment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_comment")
                        .HasDefaultValueSql("true")
                        .HasComment("Allow comment");

                    b.Property<bool?>("IsTop")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_top")
                        .HasComment("is top");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("true")
                        .HasComment("状态（0已发布，1草稿）");

                    b.Property<string>("Summary")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("summary")
                        .HasComment("article summary");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("thumbnail")
                        .HasComment("缩略图");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title")
                        .HasComment("标题");

                    b.Property<long?>("UpdateBy")
                        .HasColumnType("bigint")
                        .HasColumnName("update_by");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_time");

                    b.Property<long>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("view_count")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Id");

                    b.ToTable("article", (string)null);

                    b.HasComment("article table");
                });
#pragma warning restore 612, 618
        }
    }
}
